### ISSUE TITLE
Query channel plugin information from all available plugins and write it to the database

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga-notifications#107]
This issue is pretty much a follow-up to #82 where the corresponding PR #101 moved the channel implementation into separate processes.

The task for this issue is to actually make use of the `GetInfo` method already added. To make use of this, on startup, the daemon should list all available plugins in the plugin directory, start them and call their `GetInfo` method and write the obtained information to a new table in the database. The purpose of this table will be so that notifications-web can use it to list available channel types as well as use it to provide a form for the channel configuration and populate the `channel.config` column with corresponding JSON.

For now, I suggest the following information should be added to the plugin info and therefore the database:
- Plugin name
- Plugin version
- Author information (name, e-mail, URL)
- Configuration configuration options: a list of form fields that notifications-web should present when configuring a channel of that particular type

For completeness, my suggestion for the latter would be something like that, but the exact details should be coordinated with notifications-web. For the daemon, this will pretty much be an opaque value (it should just write the JSON into the database without interpreting it).

```json
[
    {"name": "url", "label": "RocketChat Instance", "type": "text", "required": true, "help": "Base URL of the RocketChat installation, for example https://chat.example.com/"},
    {"name": "user_id", "label": "User ID", "type": "text", "required": true, "help": "User ID associated with the access token"},
    {"name": "token", "label": "Token", "type": "password", "required": true, "help": "Personal access token for the bot user"}
]
```

**Comment by nilmerg** [comment]
I'd suggest to generalize as much as possible.

## Types

* string (single line of free text)
* text (multiple lines of free text)
* bool (yes or no)
* option (single) or options (multiple) with a property called `options` which holds a map of value/label pairs
* secret (single line of sensible information)

## Label

Should be a map of locale/message pairs. A locale should use the standard format (*language_REGION*) and it should be assumed to be encoded with UTF8. (Without the suffix in the locale)

## Help

Should be a map of locale/message pairs. A locale should use the standard format (*language_REGION*) and it should be assumed to be encoded with UTF8. (Without the suffix in the locale)

## Default

A default value should be optional. If given, the UI displays it, but doesn't write it back to the configuration.

## Required

Should be a boolean, defining whether the option is mandatory or not.

## Structure

```
{
    "name": string,
    "type": string,
    "label": object,
    ["options": object,]
    ["help": object,]
    ["default": mixed,]
    ["required": bool]
}
```
