### ISSUE TITLE
Check uses of runtime config RWMutex

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga-notifications#111]
As per the [documentation for `sync.RWMutex`](https://pkg.go.dev/sync#RWMutex), you should not recursively acquire read locks. Or in other words, the following code can dead-lock if another goroutine calls `mu.Lock()`:

```go
mu.RLock()
mu.RLock()
mu.RUnock()
mu.RUnlock()
```

Now there are a few places in the code that quickly acquire a read lock to fetch some value from the config as well as some places that keep one over a bit longer time. We have to check there's no nesting of the two.

**Comment by yhabteab** [comment]
These are all the code locations where we hold this lock, and none of them should result in a deadlock.

- `RuntimeConfig#GetSourceFromCredentials()` used exclusively by the listener
https://github.com/Icinga/icinga-notifications/blob/8ac042d729fb51fac6d607743eadbbc0355a7dcb/internal/config/runtime.go#L188-L190
https://github.com/Icinga/icinga-notifications/blob/8ac042d729fb51fac6d607743eadbbc0355a7dcb/internal/listener/listener.go#L103-L104

- `RuntimeConfig#debugVerify()` used o validate the incremental configuration updates
https://github.com/Icinga/icinga-notifications/blob/8ac042d729fb51fac6d607743eadbbc0355a7dcb/internal/config/verify.go#L13-L15
https://github.com/Icinga/icinga-notifications/blob/8ac042d729fb51fac6d607743eadbbc0355a7dcb/internal/config/runtime.go#L100-L103

- `incidents#LoadOpenIncidents()` called only on daemon startup
https://github.com/Icinga/icinga-notifications/blob/8ac042d729fb51fac6d607743eadbbc0355a7dcb/internal/incident/incidents.go#L100-L102

- `incident#ProcessEvent()` used to process every incoming events of that incident, but doesn't call any other methods which also acquire that very same lock.
https://github.com/Icinga/icinga-notifications/blob/8ac042d729fb51fac6d607743eadbbc0355a7dcb/internal/incident/incident.go#L125-L126

- `incident#RetriggerEscalations()` used to re-evaluate time-based escalations and is called in its own/separate goroutine
https://github.com/Icinga/icinga-notifications/blob/8ac042d729fb51fac6d607743eadbbc0355a7dcb/internal/incident/incident.go#L229-L230

- [`listener#DumpSchedules()`](https://github.com/Icinga/icinga-notifications/blob/main/internal/listener/listener.go#L229) a separate debugging endpoint.
https://github.com/Icinga/icinga-notifications/blob/8ac042d729fb51fac6d607743eadbbc0355a7dcb/internal/listener/listener.go#L240-L241
