### ISSUE TITLE
Avoid duplicate configuration were possible

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icinga-notifications#143]
While looking at the current state of the module, we found one potential issue of the URL for Icinga Web 2 has to be defined in two different locations. In this case it is once defined by the Icinga 2 integration utilizing a constant defined in Icinga 2 and another time in the file based configuration of the Notifications daemon. This may result in both having different values. 

I understand the logic, that every component can send event to Icinga Notifications and can include the URL while doing so, but I would hope there could be a single point of configuration for this. So perhaps working with a placeholder that is then replaced by Notifications as a single source for it. 

Perhaps it makes also sense to have it configured via the Web interface and stored in the Database instead of a file. Another idea would be then allow an override at user level or the rule set in case you have an internal and an external URL or something similar in your environment.

**Comment by oxzi** [comment]
The current Icinga 2 integration with the custom `icinga2.conf` file, specifying the Icinga Web 2 URL as `IcingaNotificationsIcingaWebUrl`, is planned to be only a temporary solution. After #112 is finalized, there might be no more use for a custom Icinga 2 configuration and the Icinga Web 2 URL is then only present in the Icinga Notifications configuration.

**Comment by julianbrost** [comment]
The aforementioned was merged, so that duplication no longer exists.
