### ISSUE TITLE
Drop `incident_history.caused_by_incident_history_id`

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga-notifications#163]
Since the introduction of internal events, there's no need for incident events to link to each other anymore.

## What needs to be done?

Drop `incident_history.caused_by_incident_history_id` and remove code to populate it. `incident_history.event_id` should in turn be not nullable.

## How is Web affected?

The column isn't actively used, but it also needs to be dropped from the corresponding model.

In the (near) future Web should still try to visualize corresponding history entries. As they share the same `event.id` it can use this to detect how to group events. But this is not planned yet. Though, it would be beneficial to already ensure that `incident_history.time` is used to indicate order. (Even if it's just a millisecond difference)

**Comment by yhabteab** [comment]
Just to make this sure, @nilmerg you're asking to undo this right as you seem to be planning now to show a trigger chain for the event.

**Comment by nilmerg** [comment]
Seems like it, yes.
