### ISSUE TITLE
Channel options with default values shouldn't be required

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga-notifications#172]
At the moment, the `email` channel requires a `sender_mail` but also defines a default for it.

In #107 I've commented that an option that defines a default, will not be written to database. Hence, it shouldn't be required as well.

We could ignore the `required` flag in the UI if a default value is provided, but I don't like that. A plugin shouldn't provide conflicting meta information.

At least, I'd call that conflicting. If it's intentional, the UI needs to handle `required with default` and `optional with default` differently.

But I'd like to propose that channels should **always** fallback automatically to their default value for an option that got none. (Just like any other commandline tool)

**Comment by oxzi** [comment]
Somehow related: the email channel defines a default for `user`, but not for `password`. When I enforced setting the defaults in the channel plugin itself, the preflight check fails:

https://github.com/Icinga/icinga-notifications/blob/3786b43c2f3f3559ff0b10426fe65fc1c069d9d6/cmd/channel/email/main.go#L103
