### ISSUE TITLE
Fix default value behavior for channel plugins

### ISSUE THREAD

**Issue by oxzi** [Icinga/icinga-notifications#205]
We (@nilmerg, @yhabteab, and I) have just discussed this offline and came to the following design conclusion:
- absent keys are resulting in using the default value and
- a `null` value results in an empty value for optional key value pairs.

Those changes must be done in the daemon or, more precisely, the channel plugins and I am going to make the necessary changes tomorrow.

_Originally posted by @oxzi in https://github.com/Icinga/icinga-notifications-web/issues/154#issuecomment-2135583142_

**Comment by yhabteab** [comment]
> > a `null` value results in an empty value for optional key value pairs.
> 
> Can you please elaborate on what this is supposed to achieve?

Initially, this was intended to indicate that the user does not want to use the default value (if any) of an optional field of a specific channel. However, this does not seem to work if GO does not decode JSON `null` values into the zero initialised value of a given type.

**Comment by oxzi** [comment]
> Note that giving `null` in JSON some meaning might become tricky in combination with Go's [`encoding/json`](https://pkg.go.dev/encoding/json) as that already has a special interpretation of `null`:

Valid point. However, when first setting a default (or fallback) value, the struct is already partially populated and gets only overwritten when a user-configured value is stored in the JSON. As no further reconfiguration takes place, this shouldn't be an issue.

**Comment by oxzi** [comment]
We discussed this again with @nilmerg and came to dropping the "`null` equals empty field" rule. @nilmerg came up with an implementation in <https://github.com/Icinga/icinga-notifications-web/pull/230>.
