### ISSUE TITLE
Persist all events transmitted by a source

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga-notifications#213]
## About

The daemon ignores state events which don't influence an incident's severity. This, with escalations in mind, is fine. Though, this also causes such events to not appear in the `event` table.

## Problem

This makes trouble shooting event rules more difficult. And since Notifications Web has a proper integration with Icinga DB Web now, it also shows the current state in an event's detail. This might show different results if compared with the latest event visible in our event overview.

## Proposal

I'd suggest to persist all events transmitted to us.

**Comment by julianbrost** [comment]
> This makes trouble shooting event rules more difficult.

Why does it do this?

The only thing that comes to my mind is more of a general question: if you change the object filter of a rule, should it be checked against all currently open incidents and if it now matches, should those notify immediately according to the new rule?

> And since Notifications Web has a proper integration with Icinga DB Web now, it also shows the current state in an event's detail. This might show different results if compared with the latest event visible in our event overview.

That issue won't go away as sources are only supposed to send state events when the state changes. (If we changed that requirement, we would have basically reinvented the IDO where every single check execution results in a write to the database.)

**Comment by nilmerg** [comment]
Arg. This was mainly a brain dump. Now, I remember I was irritated because my check didn't cause a new escalation. I looked at the event list, didn't see anything. Looked at the log, saw the "ignoring superfluous ...' entry and remembered this:

> sources are only supposed to send state events when the state changes.

And thought to myself, what a crap. But I also wondered why the integration in the related object section of the incident also showed the same state. This is because redis isn't queried in this case and so only the state in the database is visible.

So, to avoid this:

> This might show different results if compared with the latest event visible in our event overview.

We just shouldn't query redis and be done with it?

Or should we introduce a redis for notifications as well? :joy: 

--

Feel free to ignore this. It's just me babbling and not understanding our own software. -.-
