### ISSUE TITLE
wrong ip in the notifications

### ISSUE THREAD

**Issue by gurhanocaktan** [Icinga/icinga-notifications#283]
Hi guys ,

I am testing the module , in the emails I get ,
```

Object: http://localhost/icingaweb2/icingadb/service?name=dummy-process-test&host.name=Icinga-Test-Server

Incident: http://localhost/icingaweb2/notifications/incident?id=81
```

It says like this , how can I change localhost here to my server's ip address ?

**Comment by nilmerg** [comment]
This is [covered in the documentation](https://icinga.com/docs/icinga-notifications/latest/doc/03-Configuration/#icinga-web-2).

**Comment by gurhanocaktan** [comment]
You are right , thank you !
