### ISSUE TITLE
Mechanism for incremental config updates

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga-notifications#5]
Periodically fetching the full configuration from the database and searching it for changes would become infeasible quickly. Therefore, we will require a mechanism for getting notified about individual configuration changes in the database.

The exact details of the implementation are up to discussion, some proposals follow (I currently favor option 3).

## Option 1: Web notifies the daemon

The backend daemon already needs a listener for events from sources, it could just add a new endpoint that Web could ping every time it updates something.

**Pros:**
- No added latency as no polling is required.
- No cleanup needed.

**Cons:**
- Separate from the database means this connection could fail independently adding new failure scenarios.

## Option 2: Update information in affected tables

Add columns like `changed_at`/`deleted_at` to affected tables similar to [system-versioned tables](https://mariadb.com/kb/en/system-versioned-tables/) and regularly poll for rows with a higher value than the last seen one.

**Pro:**
- Tracked in the same row where the change happens, therefore reliable as the change is signaled with the same query that does the actual change.

**Cons:**
- Polling required, with a query per table that is monitored for changes.
- If timestamp are used for the value, there might be problems with diverging system times, especially if there are multiple hosts serving the web interface and they just always use `now()`, monotonic values aren't guaranteed. On the other hand using a sequence number would be annoying with MySQL as there seems to be no explicit sequence type and only one auto-increment column seems to be supported.

## Option 3: Change queue table in the database

Create a table like `config_change (id bigserial, table text, foreign_pk bigint)`. Each time Web creates/updates/deletes a row, it inserts a row into this table referring the affected row.

**Pros:**
- Notification happens via the database, thus no extra connection that can fail. Notification can happen inside a transaction with the actual change.
- Only a single table has to be polled.
- Table could be extended with columns `time`, `username`, `diff` and we would have a config change/audit log.
- Compared to the previous suggestion, the incrementing `id` column would provide reliable sequencing of changes.

**Cons:**
- Polling required, however with just one query watching for changes in all tables.
- Cleanup of the table needed (unless we actively want this as a log).

**Comment by julianbrost** [comment]
> Regardless of which way we are going to choose, a garbage collection will become necessary. The second option is going to pile up `deleted_at` objects and the third option will collect every change.

These rows still serve the purpose of providing additional information for old history entries. So I wouldn't say that garbage collection is immediately necessary with this variant. But that probably also depends a bit on the individual tables and whether these are actually referenced from the history.

One question will then arise: do we want that for every config table or just for the main ones? Like for example, if a user is added to a group, there would be two options: track each membership individually with `changed_at`/`deleted_at` columns or simply view it as a change of the group and track the change only there.

**Comment by oxzi** [comment]
While the OP mentioned temporal tables or system tables, which might look promising, those are not available in PostgreSQL. The SQL:2011 revision specifies system-versioned tables as implemented in MariaDB, but PostgreSQL currently only has [external extensions](https://wiki.postgresql.org/wiki/Temporal_Extensions) therefore.

**Comment by nilmerg** [comment]
I don't really care. Or rather, Web doesn't. Whether we'll need to update two additional columns or insert a new row in a new table, isn't a big difference.

**Comment by oxzi** [comment]
Then we're aiming at a variant of the second version with a `changed_at` column and a boolean `deleted` column. In a first naive idea, this should affect all tables listed here:
https://github.com/Icinga/icinga-notifications/blob/8ca9efde9db7397ebc0bd74b1116bd05e5727322/internal/config/runtime.go#L57-L66
