### ISSUE TITLE
`membership_hash` column required for `schedule_member` table

### ISSUE THREAD

**Issue by raviks789** [Icinga/icinga-notifications#83]
To efficiently update timeperiod entries, we need to assign a membership hash based on recipients for the given schedule. 

Currently a new timeperiod has been created each time a new timeperiod entry has been added instead of using the existing timeperiod for the given schedule and the combination of users and usergroups. Hence, adding the `membership_hash` to the `schedule_member` solves this issue.

**Comment by julianbrost** [comment]
Feel free to create a PR. That column will only be used by the web module, so no changes apart from the schema file (and a corresponding upgrade file) are needed in this repo.
